### ISSUE TITLE
Website: request to add new page "Third party projects using codesearch.debian.net"

### ISSUE THREAD

**Issue by nbenitez** [Debian/dcs#105]
I think it would be useful/interesting to list those so people can learn cleverly ways in which codesearch.debian.net service is being used.

Initial list could be:
https://salsa.debian.org/debian/codesearch-cli 
https://salsa.debian.org/aviau/identify-incomplete-xs-go-import-path
https://gitlab.gnome.org/nbenitez/gnome-codesearch

If you like the idea I can submit a PR.

**Comment by stapelberg** [comment]
Yes, I think that’d be a good idea. Looking forward to your PR,

**Comment by nbenitez** [comment]
Done, thank you :slightly_smiling_face:

**Comment by stapelberg** [comment]
Closing this issue as the page has been added.
