### ISSUE TITLE
Defective grouping for Debian source packages on Firefox?

### ISSUE THREAD

**Issue by lechner** [Debian/dcs#113]
Please search for `Dh_Haskell.sh` (literal) and then check the box `Group search results by Debian source package`. Where did the hit go for `haskell-iso8601-time`?

Seen in Firefox `91.6.0esr (64 bit)`, but it does not happen in Chromium. Thanks!

**Comment by stapelberg** [comment]
> Please search for `Dh_Haskell.sh` (literal)

https://codesearch.debian.net/search?q=Dh_Haskell.sh&literal=1

> Where did the hit go for `haskell-iso8601-time`?

For me, it’s on page 2:

![firefox](https://user-images.githubusercontent.com/55506/156419326-4e22418a-3e4f-4146-9039-9064792d9159.jpg)

I tested this with Firefox 95.0.2 on Arch Linux. So it seems to be specific to the older Firefox version you’re using.

Feel free to contribute a fix, but I’ll just recommend people use an up-to-date browser version for now :)

**Comment by lechner** [comment]
Okay, thanks!
