### ISSUE TITLE
Incorrect highlight for matches on the first line

### ISSUE THREAD

**Issue by nthykier** [Debian/dcs#119]
If your search happens to match the first line in the file, the _second_ line is highlighted as a match instead of the first.

Try searching for `bin/sh` (as an example that easily triggers this bug).  The expect result is that the `#!/bin/sh` line of all scripts is highlighted, but it never is. Instead, if the second line is non-empty, it will be boldface as if that is the line that matches.

**Comment by nthykier** [comment]
![Screenshot_2022-10-21_17-02-44](https://user-images.githubusercontent.com/429402/197227703-71c55d1a-3abd-47b4-b5ba-914b9361dba9.png)

**Comment by stapelberg** [comment]
Tracked it down to an issue with the `index.FiveLines()` function (which is only used when positional mode is enabled, which wasn’t the case in the `dcs-localdcs` test environment, so this took a while to narrow down…).
