### ISSUE TITLE
Result view looks broken for queries with few results

### ISSUE THREAD

**Issue by Merovius** [Debian/dcs#43]
I tried the query "nfc_initiator_transceive_bytes" today, which only has one page of results, this is a screenshot from the end of the page:
![Screenshot](http://merovius.de/codesearch_scrot.png)
I am fairly certain that it should not look like that.

When I tried "append_dot_mydomain" as a query with probably few results, I saw similar problems.

**Comment by stapelberg** [comment]
As discussed in person, I can’t reproduce this. It only happens in one of your Firefox profiles, and even disabling all extensions does not make a difference.

Closing this, please reopen if you can find good steps to reproduce.
