### ISSUE TITLE
Include more information with the result JSON URI

### ISSUE THREAD

**Issue by BenBE** [Debian/dcs#46]
It would be nice to get some more information on the result (not only the packages) when querying the JSON file. It'd be ideal if the JSON could optionally include the files that contained the matches as a sub-array per package. To stay compatible the packages.json part of the generated link of the result page could be extended to allow "files.json" which will provide these addtional information.

**Comment by stapelberg** [comment]
I’m not sure I understand. Can you list the specific use-case and explain why the data that DCS currently generates is not enough to cover your use-case?

**Comment by stapelberg** [comment]
I’m closing this due to the lack of reply. Without additional information, I have nothing to go on here.
