### ISSUE TITLE
page list at bottom when grouping by source package

### ISSUE THREAD

**Issue by jwilk** [Debian/dcs#50]
(I reported this already to Michael in private mail, but never got any reply. I'm filing it here in hope in won't get lost this time.)

I wanted to try out the "Group results by source package" feature.
But unfortunately when it's enabled, the list of pages is available only at the top of the page.
Could you add it also to the bottom of the page, where it would be much more convenient?

**Comment by stapelberg** [comment]
Sorry for the lack of a response. I received and read your private email about it, haven’t gotten around to implement it yet. I hope I can work on a bunch of DCS feature requests/issues soonish.
