### ISSUE TITLE
non-JS search page includes HTTP resources

### ISSUE THREAD

**Issue by jwilk** [Debian/dcs#58]
If you have JS disabled, search pages (such as https://codesearch.debian.net/search?q=mooooo) include HTTP resources that makes Iceweasel upset:
> Iceweasel has blocked parts of this page that are not secure

I guess the problematic code is:

```html
<link rel="stylesheet" href="http://yandex.st/highlightjs/7.0/styles/default.min.css">
<script src="http://yandex.st/highlightjs/7.0/highlight.min.js"></script>
```

I think it should be safe to remove these lines, as you don't get any syntax highlighting with JS disabled anyway.

**Comment by stapelberg** [comment]
I think we should rather switch to schema-less URLs for them. Given that the distinction between javascript and non-javascript is made _in javascript_, we can’t simply remove parts of the page.
