### ISSUE TITLE
Ditch postgresql

### ISSUE THREAD

**Issue by stapelberg** [Debian/dcs#67]
Having to set up PostgreSQL makes a quick hacking session and integration tests more complicated. We only use the most basic features (`SUM`) and load the entire data set when starting the `dcs-source-backend` process.

* [ ] Instead of downloading the UDD dump, we should switch to using http://popcon.debian.org/sourcemax/by_inst.gz directly
 * [ ] Clarify why the number of rows is different between the two
 * [ ] Make dcs-compute-ranking use the popcon data instead of querying PostgreSQL
* [ ] Make `ranking/pre-ranking.go` load ranking data formatted in JSON.

**Comment by tfheen** [comment]
]] Michael Stapelberg 

> Having to set up PostgreSQL makes a quick hacking session and
> integration tests more complicated. We only use the most basic
> features (SUM) and load the entire data set when starting the
> dcs-source-backend process.

For integration tests, I'd like to point you at pg_virtualenv.

-- 
Tollef Fog Heen
UNIX is user friendly, it's just picky about who its friends are
