### ISSUE TITLE
regex not allowed with package/pkg keyword?

### ISSUE THREAD

**Issue by legrostdg** [Debian/dcs#87]
`pkg:restic test` on https://codesearch.debian.net returns results while `pkg:restic.* test` does not. The FAQ seems to imply it should work...

**Comment by stapelberg** [comment]
Thanks for the report. I’m fairly busy until at least this weekend, so if you want to go ahead and investigate, that’d be great. See https://github.com/Debian/dcs/blob/master/howto/hacking.md for instructions.

**Comment by stapelberg** [comment]
The code already contains a note about this not being a regexp: https://github.com/Debian/dcs/blob/9fb41056c2393d98e942439c32ae88d68f33231a/cmd/dcs-source-backend/source-backend.go#L96

Given that people expect it to be a regexp, I’d say we should turn it into one.

**Comment by stapelberg** [comment]
Deployed. E.g. https://codesearch.debian.net/search?q=xcb_create+package%3Ai3.* works now.
