### ISSUE TITLE
Create and/or document a rest api

### ISSUE THREAD

**Issue by aviau** [Debian/dcs#89]
Hello!

Is there some kind of rest API where I can make searches?

There is a [tool](https://salsa.debian.org/aviau/identify-incomplete-xs-go-import-path) that I built for pkg-go that uses dcs. It tries to identify golang source packages that should have several import paths in XS-Go-Import-Path. 

I had to hardcode a link to search results in the code.

```python
def get_matching_source_packages():
    # Hardcoded result of this query on codesearch.debian.net:
    # "gocode path:debian/.*\.links package:golang.*"
    r = requests.get(
        "https://codesearch.debian.net/results/f9d797d3d9f1af9b/packages.json",
    )
    source_packages = r.json()["Packages"]
    return source_packages
```

Is there something I am missing?

**Comment by stapelberg** [comment]
For the time being, there is no API. This hasn’t stopped people from using the websocket interface directly, though, see e.g. https://github.com/FedericoCeratto/debian-code-search-cli/blob/master/codesearch_cli.py

We sure can talk about adding a proper API, in which case I’d suggest using gRPC.

Side note: for pkg-go specifically, I found that cloning all repositories and then just using grep locally to be a viable strategy. I can clean up and share the tooling I used to obtain (and fix up) the Vcs-Git URLs for all packages which are currently in the archive.

**Comment by yugr** [comment]
Thanks for mentioning `codesearch_cli`, would be enough for my needs (I develop various code analyzers and use Codesearch to lookup packages which are applicable for analysis).

**Comment by stapelberg** [comment]
I have been working on an HTTP API, described in OpenAPI.

Please find the preview version at https://codesearch.debian.net/apikeys/,
and let me know if you have any feedback.

There is also a gRPC API that is slightly lower-level,
in case the OpenAPI one is too high-level.

I would like to announce the OpenAPI API more widely in a few days.

Thanks,

cc @nbenitez @yugr @aviau

**Comment by stapelberg** [comment]
Sent https://salsa.debian.org/debian/codesearch-cli/-/merge_requests/1 to move codesearch-cli to OpenAPI

**Comment by jwilk** [comment]
> Please find the preview version at https://codesearch.debian.net/apikeys/,

It says "404 page not found".

**Comment by stapelberg** [comment]
Try again now. Not sure why this page disappears from time to time. Will look into it in more detail.

**Comment by stapelberg** [comment]
> Try again now. Not sure why this page disappears from time to time. Will look into it in more detail.

commit https://github.com/Debian/dcs/commit/12b99fbc5d15bfb042cd375d16a5c6b14e17aa82 should fix this

I have also set up automated monitoring for the /apikeys/ handler, just in case something else is wrong (now and/or in the future)… :)
