### ISSUE TITLE
search doesn’t work without javascript

### ISSUE THREAD

**Issue by stapelberg** [Debian/dcs#90]
07:18 @pabs> sECuRE: I'm told this URL produces zero results when JavaScript is turned on but works when it is turned off 
             https://codesearch.debian.net/search?q=ftp%3A%2F%2F%28security%7Cftp%29%5C.debian%5C.org
07:18 @pabs> would you mind investigating that?

**Comment by stapelberg** [comment]
The URL works fine for me in Firefox 58 with Javascript disabled:

![2018-03-12-175438_2906x4006_scrot](https://user-images.githubusercontent.com/55506/37297632-72f9e3d6-261e-11e8-80de-c1f30f39bc79.png)

**Comment by pabs3** [comment]
@lamby said it was broken with JavaScript turned *on* and gave this proof:

https://i.imgur.com/9YkzfdT.jpg

It worked for me and one other person with JavaScript turned off. I was using Firefox 52 ESR.

**Comment by stapelberg** [comment]
Ah, sorry, I misread the original issue.

I can confirm that the search query incorrectly produces no results. This is because the URL is cleaned, turning the `ftp%3A%2F%2F` into `ftp:/`, which is not intended.

I’ll take a stab at fixing this.

**Comment by stapelberg** [comment]
This is now fixed. You might need to clear your caches and/or use shift-reload to pick up the new javascript.
