### ISSUE TITLE
package: keyword doesn't do exact matches. "filter by package" should use regex anchors

### ISSUE THREAD

**Issue by dkg** [Debian/dcs#92]
if you do a search for "fiat package:nss" you get results from many packages, including `openssl` (i guess because it has `nss` in the name).

but then the webui has a link that lets you "filter by package", including the "nss" package.  the link for filtering by the "nss" package just adds another `package:nss` to the query string, which clearly doesn't limit the query.

Instead, it should add `package:^nss$` to the search string.

**Comment by stapelberg** [comment]
This is a consequence of #87 :).

**Comment by stapelberg** [comment]
Now fixed and deployed. You may need to clear caches and/or unregister Service Workers to see the effect.
